version: '3.7'
services:
  mysql:
    image: mysql:8
    command: ["--default-authentication-plugin=mysql_native_password", "--innodb-use-native-aio=0", "--sql-mode=ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"]
    environment:
      MYSQL_ROOT_PASSWORD: abcdef
      MYSQL_USER: sw
      MYSQL_PASSWORD: abcdef
      MYSQL_DATABASE: sw
    networks:
      - sw
    ports:
      - 3001:3306

  web:
    build:
      dockerfile: Dockerfile
    container_name: security-workshop
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - 3000:80
    networks:
      - sw
    depends_on:
      - mysql

networks:
  sw:
    driver: bridge
